# Generated by Django 5.1.15 on 2026-07-02 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('service_type', models.CharField(choices=[('search_console', 'Google Search Console'), ('analytics', 'Google Analytics 4'), ('trends', 'Google Trends')], max_length=30)),
                ('external_id', models.CharField(max_length=500)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_properties', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'integrations_google_properties',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'service_type', 'external_id'), name='uniq_google_property')],
            },
        ),
        migrations.CreateModel(
            name='GoogleServiceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('service_type', models.CharField(choices=[('search_console', 'Google Search Console'), ('analytics', 'Google Analytics 4'), ('trends', 'Google Trends')], max_length=30)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('config_required', 'Configuration Required'), ('waiting_authorization', 'Waiting for Authorization'), ('connected', 'Connected'), ('error', 'Error')], db_index=True, default='not_connected', max_length=30)),
                ('connected_account_email', models.CharField(blank=True, default='', max_length=320)),
                ('property_id', models.CharField(blank=True, default='', max_length=500)),
                ('property_label', models.CharField(blank=True, default='', max_length=500)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('encrypted_refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('oauth_state', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_connections', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'integrations_google_connections',
                'indexes': [models.Index(fields=['tenant', 'service_type', 'status'], name='integration_tenant__27c691_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'service_type'), name='uniq_google_connection_per_tenant_service')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('service_type', models.CharField(choices=[('search_console', 'Google Search Console'), ('analytics', 'Google Analytics 4'), ('trends', 'Google Trends')], max_length=30)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=10)),
                ('retrieved_at', models.DateTimeField()),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('processed_data', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('automation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_syncs', to='automation.automationjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_syncs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'integrations_sync_records',
                'indexes': [models.Index(fields=['tenant', 'service_type', 'retrieved_at'], name='integration_tenant__3ad76d_idx'), models.Index(fields=['tenant', 'sync_status'], name='integration_tenant__8c2e38_idx')],
            },
        ),
    ]
