# Generated by Django 5.2.14 on 2026-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'מנהל'), ('team', 'חבר צוות'), ('customer', 'לקוח')], default='customer', max_length=20),
        ),
    ]
