# Generated by Django 5.1.15 on 2026-07-01 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('page_type', models.CharField(choices=[('landing_page', 'Landing page'), ('blog', 'Blog article'), ('resource', 'Resource'), ('industry', 'Industry'), ('template_preview', 'Template preview')], default='landing_page', max_length=30)),
                ('block_schema', models.JSONField(default=list, help_text='Default block definitions [{type, config}]')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_templates', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_templates',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('page_type', models.CharField(choices=[('landing_page', 'Landing page'), ('blog', 'Blog article'), ('resource', 'Resource'), ('industry', 'Industry'), ('template_preview', 'Template preview')], default='landing_page', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('locale', models.CharField(default='he', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200)),
                ('full_path', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('published_version', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.page')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='content.contenttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_pages',
            },
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('link_type', models.CharField(choices=[('related', 'Related'), ('cross_sell', 'Cross-sell'), ('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('anchor_text', models.CharField(blank=True, default='', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_automatic', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_links', to='tenancy.tenant')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='content.page')),
                ('target_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_links', to='content.page')),
            ],
            options={
                'db_table': 'content_internal_links',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('cta', 'Call to action'), ('faq', 'FAQ'), ('image', 'Image'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('form', 'Form'), ('custom', 'Custom')], default='text', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.page')),
            ],
            options={
                'db_table': 'content_blocks',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200)),
                ('full_path', models.CharField(max_length=500)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('blocks_snapshot', models.JSONField(default=list)),
                ('terms_snapshot', models.JSONField(default=list)),
                ('change_summary', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_versions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.page')),
            ],
            options={
                'db_table': 'content_page_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('kind', models.CharField(choices=[('category', 'Category'), ('tag', 'Tag'), ('custom', 'Custom')], default='category', max_length=20)),
                ('is_hierarchical', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Page may have multiple terms')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomies', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_taxonomies',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('full_path', models.CharField(blank=True, default='', help_text='Hierarchical path segment', max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.taxonomyterm')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='content.taxonomy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_terms', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_taxonomy_terms',
            },
        ),
        migrations.CreateModel(
            name='PageTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_terms', to='content.page')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_terms', to='content.taxonomyterm')),
            ],
            options={
                'db_table': 'content_page_terms',
            },
        ),
        migrations.AddConstraint(
            model_name='contenttemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_content_template_slug'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['tenant', 'status'], name='content_pag_tenant__984989_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['tenant', 'page_type'], name='content_pag_tenant__f63b02_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['tenant', 'parent'], name='content_pag_tenant__3507c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('tenant', 'full_path', 'locale'), name='uniq_page_path_locale'),
        ),
        migrations.AddIndex(
            model_name='internallink',
            index=models.Index(fields=['tenant', 'source_page'], name='content_int_tenant__81cac8_idx'),
        ),
        migrations.AddIndex(
            model_name='internallink',
            index=models.Index(fields=['tenant', 'target_page'], name='content_int_tenant__55d093_idx'),
        ),
        migrations.AddConstraint(
            model_name='internallink',
            constraint=models.UniqueConstraint(fields=('source_page', 'target_page', 'link_type'), name='uniq_internal_link'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['page', 'sort_order'], name='content_blo_page_id_8f62b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(fields=('page', 'version_number'), name='uniq_page_version_number'),
        ),
        migrations.AddConstraint(
            model_name='taxonomy',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_content_taxonomy_slug'),
        ),
        migrations.AddIndex(
            model_name='taxonomyterm',
            index=models.Index(fields=['tenant', 'taxonomy'], name='content_tax_tenant__0e1509_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyterm',
            index=models.Index(fields=['tenant', 'full_path'], name='content_tax_tenant__2efbe2_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyterm',
            constraint=models.UniqueConstraint(fields=('tenant', 'taxonomy', 'slug'), name='uniq_taxonomy_term_slug'),
        ),
        migrations.AddConstraint(
            model_name='pageterm',
            constraint=models.UniqueConstraint(fields=('page', 'term'), name='uniq_page_term'),
        ),
    ]
