# Generated by Django 5.1.15 on 2026-07-01 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttemplate',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='Theme tokens: colors, fonts, spacing overrides'),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='theme_slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Content author attribution (may differ from created_by)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('rich_text', 'Rich text'), ('cta', 'Call to action'), ('faq', 'FAQ'), ('image', 'Image'), ('gallery', 'Gallery'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('form', 'Form'), ('contact_form', 'Contact form'), ('custom', 'Custom')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='contenttemplate',
            name='page_type',
            field=models.CharField(choices=[('landing_page', 'Landing page'), ('blog', 'Blog article'), ('static', 'Static page'), ('resource', 'Resource'), ('industry', 'Industry'), ('template_preview', 'Template preview')], default='landing_page', max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('landing_page', 'Landing page'), ('blog', 'Blog article'), ('static', 'Static page'), ('resource', 'Resource'), ('industry', 'Industry'), ('template_preview', 'Template preview')], default='landing_page', max_length=30),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=1000)),
                ('alt_text', models.CharField(blank=True, default='', max_length=300)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='tenancy.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_media_assets',
                'indexes': [models.Index(fields=['tenant', 'media_type'], name='content_med_tenant__50d323_idx')],
            },
        ),
    ]
