# Generated by Django 5.1.15 on 2026-07-02 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_queues', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'automation_queues',
            },
        ),
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('job_type', models.CharField(choices=[('keyword_research', 'Keyword Research'), ('keyword_sync', 'Keyword Sync'), ('competition_scan', 'Competition Scan'), ('serp_scan', 'SERP Scan'), ('search_console_sync', 'Search Console Sync'), ('google_trends_sync', 'Google Trends Sync'), ('generate_landing_page', 'Generate Landing Page'), ('generate_blog_article', 'Generate Blog Article'), ('generate_faq', 'Generate FAQ'), ('generate_metadata', 'Generate Metadata'), ('generate_schema', 'Generate Schema'), ('generate_internal_links', 'Generate Internal Links'), ('generate_alt_text', 'Generate ALT Text'), ('generate_images', 'Generate Images'), ('optimize_images', 'Optimize Images'), ('compress_images', 'Compress Images'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('schedule_publishing', 'Schedule Publishing'), ('archive', 'Archive'), ('update_sitemap', 'Update Sitemap'), ('ping_search_engines', 'Ping Search Engines'), ('refresh_metrics', 'Refresh Metrics'), ('generate_reports', 'Generate Reports'), ('broken_link_scan', 'Broken Link Scan'), ('seo_audit', 'SEO Audit'), ('email_campaign', 'Email Campaign'), ('whatsapp_campaign', 'WhatsApp Campaign'), ('sms_campaign', 'SMS Campaign'), ('lead_follow_up', 'Lead Follow-up'), ('backup', 'Backup'), ('health_check', 'Health Check'), ('cleanup', 'Cleanup'), ('cache_refresh', 'Cache Refresh')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], db_index=True, default='queued', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('requires_approval', models.BooleanField(default=False)),
                ('auto_publish_enabled', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('parent_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='automation.automationjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_jobs', to='tenancy.tenant')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='automation.automationqueue')),
            ],
            options={
                'db_table': 'automation_jobs',
            },
        ),
        migrations.CreateModel(
            name='AutomationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('schedule_type', models.CharField(choices=[('now', 'Run Now'), ('specific', 'Specific Date'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('every_minutes', 'Every X Minutes'), ('every_hours', 'Every X Hours'), ('every_days', 'Every X Days'), ('cron', 'Cron Expression')], default='now', max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=120)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='automation.automationjob')),
            ],
            options={
                'db_table': 'automation_schedules',
            },
        ),
        migrations.CreateModel(
            name='AutomationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('job_type', models.CharField(choices=[('keyword_research', 'Keyword Research'), ('keyword_sync', 'Keyword Sync'), ('competition_scan', 'Competition Scan'), ('serp_scan', 'SERP Scan'), ('search_console_sync', 'Search Console Sync'), ('google_trends_sync', 'Google Trends Sync'), ('generate_landing_page', 'Generate Landing Page'), ('generate_blog_article', 'Generate Blog Article'), ('generate_faq', 'Generate FAQ'), ('generate_metadata', 'Generate Metadata'), ('generate_schema', 'Generate Schema'), ('generate_internal_links', 'Generate Internal Links'), ('generate_alt_text', 'Generate ALT Text'), ('generate_images', 'Generate Images'), ('optimize_images', 'Optimize Images'), ('compress_images', 'Compress Images'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('schedule_publishing', 'Schedule Publishing'), ('archive', 'Archive'), ('update_sitemap', 'Update Sitemap'), ('ping_search_engines', 'Ping Search Engines'), ('refresh_metrics', 'Refresh Metrics'), ('generate_reports', 'Generate Reports'), ('broken_link_scan', 'Broken Link Scan'), ('seo_audit', 'SEO Audit'), ('email_campaign', 'Email Campaign'), ('whatsapp_campaign', 'WhatsApp Campaign'), ('sms_campaign', 'SMS Campaign'), ('lead_follow_up', 'Lead Follow-up'), ('backup', 'Backup'), ('health_check', 'Health Check'), ('cleanup', 'Cleanup'), ('cache_refresh', 'Cache Refresh')], max_length=64)),
                ('default_config', models.JSONField(default=dict)),
                ('steps_schema', models.JSONField(default=list)),
                ('requires_approval', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_templates', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'automation_templates',
            },
        ),
        migrations.AddField(
            model_name='automationjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='automation.automationtemplate'),
        ),
        migrations.CreateModel(
            name='AutomationWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('worker_id', models.CharField(max_length=120, unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('offline', 'Offline'), ('paused', 'Paused')], default='idle', max_length=16)),
                ('cpu_time_ms', models.PositiveIntegerField(default=0)),
                ('memory_mb', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workers', to='automation.automationjob')),
            ],
            options={
                'db_table': 'automation_workers',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('execution_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationjob')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.automationworker')),
            ],
            options={
                'db_table': 'automation_executions',
            },
        ),
        migrations.CreateModel(
            name='AutomationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('definition', models.JSONField(default=list, help_text='Ordered steps with dependencies')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_workflows', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'automation_workflows',
            },
        ),
        migrations.AddField(
            model_name='automationjob',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='automation.automationworkflow'),
        ),
        migrations.CreateModel(
            name='AutomationJobStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('step_order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('step_type', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('waiting_approval', 'Waiting Approval')], default='pending', max_length=32)),
                ('requires_approval', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.automationjob')),
            ],
            options={
                'db_table': 'automation_job_steps',
                'ordering': ['step_order'],
                'constraints': [models.UniqueConstraint(fields=('job', 'step_order'), name='uniq_automation_job_step_order')],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.automationexecution')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationjob')),
            ],
            options={
                'db_table': 'automation_logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='automation__job_id_76a814_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], default='in_app', max_length=16)),
                ('notification_type', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('approval_required', 'Approval Required'), ('cancelled', 'Cancelled'), ('started', 'Started')], max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='automation.automationjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_notifications', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_notifications',
                'indexes': [models.Index(fields=['tenant', 'user', 'read_at'], name='automation__tenant__0d53cf_idx'), models.Index(fields=['user', 'created_at'], name='automation__user_id_495bcb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='automationqueue',
            index=models.Index(fields=['tenant', 'is_default'], name='automation__tenant__b6d78b_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationqueue',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_automation_queue_slug'),
        ),
        migrations.AddIndex(
            model_name='automationschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='automation__is_acti_ba431e_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_automation_template_slug'),
        ),
        migrations.AddIndex(
            model_name='automationworker',
            index=models.Index(fields=['status', 'last_heartbeat'], name='automation__status_4d1c40_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['job', 'created_at'], name='automation__job_id_04ecf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationexecution',
            constraint=models.UniqueConstraint(fields=('job', 'execution_number'), name='uniq_automation_execution_number'),
        ),
        migrations.AddConstraint(
            model_name='automationworkflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug', 'version'), name='uniq_automation_workflow_version'),
        ),
        migrations.AddIndex(
            model_name='automationjob',
            index=models.Index(fields=['tenant', 'status', 'priority', 'created_at'], name='automation__tenant__52a4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='automationjob',
            index=models.Index(fields=['tenant', 'job_type'], name='automation__tenant__380640_idx'),
        ),
        migrations.AddIndex(
            model_name='automationjob',
            index=models.Index(fields=['queue', 'status'], name='automation__queue_i_21bd11_idx'),
        ),
    ]
