# Generated by Django 5.1.15 on 2026-07-09 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('evolution', 'Evolution API'), ('meta_cloud', 'Meta Cloud API'), ('twilio', 'Twilio')], default='evolution', max_length=30)),
                ('status', models.CharField(choices=[('not_connected', 'Not connected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], db_index=True, default='not_connected', max_length=30)),
                ('instance_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('qr_status', models.CharField(choices=[('unavailable', 'Unavailable'), ('pending', 'Pending'), ('scanned', 'Scanned'), ('expired', 'Expired')], default='unavailable', max_length=30)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'WhatsApp connection status',
                'verbose_name_plural': 'WhatsApp connection statuses',
                'db_table': 'whatsapp_connection_status',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('locale', models.CharField(blank=True, default='', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'whatsapp_conversations',
                'indexes': [models.Index(fields=['visitor_id', 'status', 'created_at'], name='whatsapp_co_visitor_8c3452_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.conversation')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='whatsapp_me_convers_bc8c2b_idx')],
            },
        ),
    ]
