# Generated by Django 5.1.15 on 2026-07-01 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOGlobalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('default_title', models.CharField(blank=True, default='', max_length=200)),
                ('default_description', models.TextField(blank=True, default='')),
                ('default_keywords', models.TextField(blank=True, default='')),
                ('default_author', models.CharField(blank=True, default='', max_length=200)),
                ('default_language', models.CharField(blank=True, default='he', max_length=10)),
                ('robots_policy', models.CharField(blank=True, default='index,follow', help_text='e.g. index,follow or noindex,nofollow', max_length=50)),
                ('canonical_base_url', models.URLField(blank=True, default='')),
                ('default_og_image', models.URLField(blank=True, default='')),
                ('default_twitter_image', models.URLField(blank=True, default='')),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('organization_logo', models.URLField(blank=True, default='')),
                ('organization_url', models.URLField(blank=True, default='')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'seo_global_settings',
            },
        ),
        migrations.CreateModel(
            name='SEORedirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('from_path', models.CharField(max_length=500)),
                ('to_path', models.CharField(max_length=500)),
                ('status_code', models.IntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_redirects', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'seo_redirects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'from_path'), name='uniq_seo_redirect_from_path')],
            },
        ),
        migrations.CreateModel(
            name='SEOSlug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('locale', models.CharField(default='he', max_length=10)),
                ('content_type', models.CharField(choices=[('static', 'Static page'), ('landing_page', 'Landing page'), ('blog', 'Blog article'), ('industry', 'Industry'), ('template', 'Template'), ('resource', 'Resource')], default='static', max_length=30)),
                ('content_id', models.UUIDField(blank=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_slugs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'seo_slugs',
                'indexes': [models.Index(fields=['tenant', 'content_type'], name='seo_slugs_tenant__e15544_idx'), models.Index(fields=['tenant', 'path'], name='seo_slugs_tenant__e533f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug', 'locale'), name='uniq_seo_slug_per_tenant_locale')],
            },
        ),
    ]
