# Generated by Django 5.2.14 on 2026-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0007_aichangerequest_archived_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichangerequest',
            name='publish_scope',
            field=models.CharField(blank=True, choices=[('live', 'אתר ראשי (Django)'), ('manage', 'דשבורד ניהול בלבד'), ('mixed', 'אתר + ניהול'), ('unknown', 'לא ידוע')], max_length=20, verbose_name='היכן השינוי נראה'),
        ),
        migrations.AlterField(
            model_name='aichangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'טיוטה'), ('generating', 'מייצר diff'), ('diff_ready', 'מוכן לבדיקה'), ('approved', 'אושר ליצירת PR'), ('pr_creating', 'יוצר PR'), ('pr_created', 'PR נוצר'), ('pr_merged', 'מוזג ל-main'), ('rejected', 'נדחה'), ('failed', 'נכשל'), ('cancelled', 'בוטל'), ('archived', 'הוסר מהרשימה')], db_index=True, default='draft', max_length=20),
        ),
    ]
