# Generated by Django 5.2.14 on 2026-05-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120, verbose_name='אירוע')),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'היסטוריית פעולות',
                'verbose_name_plural': 'היסטוריות פעולות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 ספרות אחרונות')),
                ('card_brand', models.CharField(blank=True, max_length=30, verbose_name='מותג כרטיס')),
                ('card_holder', models.CharField(blank=True, max_length=120, verbose_name='שם בעל הכרטיס')),
                ('expiry_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiry_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('balance_ils', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='יתרה ₪')),
                ('total_topup_ils', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ הפקדות')),
                ('total_charge_ils', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ חיובים')),
                ('is_verified', models.BooleanField(default=False, verbose_name='מאומת')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'חשבון אשראי',
                'verbose_name_plural': 'חשבונות אשראי',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'אימייל'), ('push', 'התראה'), ('system', 'מערכת')], default='system', max_length=20)),
                ('subject', models.CharField(max_length=200, verbose_name='נושא')),
                ('body', models.TextField(verbose_name='תוכן')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הודעה',
                'verbose_name_plural': 'הודעות',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='ת.ז.')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='עיר')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='כתובת')),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('locked', 'נעול'), ('pending', 'ממתין')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='הערות פנימיות')),
                ('subscription_type', models.CharField(blank=True, max_length=40, verbose_name='סוג מנוי')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'פרופיל לקוח',
                'verbose_name_plural': 'פרופילי לקוחות',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='מספר הזמנה')),
                ('draw_name', models.CharField(blank=True, max_length=80, verbose_name='הגרלה')),
                ('forms_count', models.PositiveIntegerField(default=1, verbose_name='טפסים')),
                ('amount_ils', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום ₪')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('paid', 'שולם'), ('printing', 'בדפוס'), ('shipped', 'נשלח'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('place_order', 'ביצוע הזמנות'), ('use_wallet', 'שימוש בארנק'), ('view_wins', 'צפייה בזכיות'), ('subscription', 'מנוי פעיל'), ('print_export', 'ייצוא להדפסה')], max_length=40)),
                ('is_granted', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הרשאה',
                'verbose_name_plural': 'הרשאות',
                'unique_together': {('customer', 'permission')},
            },
        ),
    ]
