# Generated by Django 5.0.6 on 2026-06-01 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_ils',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='עמלה'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_double',
            field=models.BooleanField(default=False, verbose_name='כפול'),
        ),
        migrations.AddField(
            model_name='order',
            name='lottery_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='מספר הגרלה'),
        ),
        migrations.AddField(
            model_name='order',
            name='sets_json',
            field=models.JSONField(blank=True, default=list, verbose_name='טבלאות'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_price_ils',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='מחיר טבלה'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('weekly', 'שבועי'), ('monthly', 'חודשי')], max_length=20)),
                ('price_ils', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='active', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('stripe_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'מנוי',
                'verbose_name_plural': 'מנויים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.PositiveSmallIntegerField()),
                ('n2', models.PositiveSmallIntegerField()),
                ('n3', models.PositiveSmallIntegerField()),
                ('n4', models.PositiveSmallIntegerField()),
                ('n5', models.PositiveSmallIntegerField()),
                ('n6', models.PositiveSmallIntegerField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_combos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'צירוף מאושר',
                'verbose_name_plural': 'צירופים מאושרים',
                'indexes': [models.Index(fields=['used'], name='portal_appr_used_c838c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LottoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.CharField(max_length=10)),
                ('set_index', models.PositiveIntegerField()),
                ('n1', models.PositiveSmallIntegerField()),
                ('n2', models.PositiveSmallIntegerField()),
                ('n3', models.PositiveSmallIntegerField()),
                ('n4', models.PositiveSmallIntegerField()),
                ('n5', models.PositiveSmallIntegerField()),
                ('n6', models.PositiveSmallIntegerField()),
                ('strong', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto_sets', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotto_sets', to='portal.subscription')),
            ],
            options={
                'verbose_name': 'סט לוטו',
                'verbose_name_plural': 'סטים לוטו',
                'ordering': ['draw_date', 'set_index'],
                'unique_together': {('customer', 'draw_date', 'set_index')},
            },
        ),
    ]
