export type EditorialLocale = "he" | "en" | "ar";

const COPY = {
  he: {
    metaTitle: "Mendeles Insights — בלוג",
    metaDescription: "תובנות, מדריכים ומחקר לצמיחה דיגיטלית — בלוג Mendeles Insights.",
    mastheadKicker: "Mendeles Insights",
    mastheadTitle: "חדשות מנדלס",
    mastheadSubtitle: "חדשות ומאמרים מעניינים מהארץ ומהעולם",
    articles: "מאמרים",
    categories: "קטגוריות",
    lastUpdate: "עדכון אחרון",
    allArticles: "כל המאמרים",
    inArchive: "במאגר",
    noResults: "לא נמצאו מאמרים עבור הסינון הנוכחי.",
    loadMore: "טען עוד מאמרים",
    featured: "מומלץ",
    readArticle: "קרא את המאמר",
    readMore: "קרא עוד",
    readingMinutes: "דקות קריאה",
    noDate: "ללא תאריך",
    team: "צוות Mendeles",
    search: "חיפוש",
    newsletter: "הרשמה לניוזלטר",
    navLabel: "קטגוריות בלוג",
    siteNavLabel: "ניווט ראשי",
    home: "מנדלס",
    blog: "בלוג",
    tools: "כלים",
    breaking: "מבזק",
    sportsDesk: "מדור ספורט",
    sportsSubtitle: "כתבות מתורגמות וניתוחים על כדורגל ועולם הספורט",
    bookmarkAdd: "שמור סימניה",
    bookmarkRemove: "הסר סימניה",
    demoNotice: "מציגים תוכן הדגמה — פרסמו מאמרים מה-workspace כדי להחליף.",
    demoNoticeTitle: "תצוגת בלוג לדוגמה",
    demoNoticeBody: "אין עדיין מאמרים מפורסמים בפרודקשן. מוצגים מאמרי עריכה לדוגמה. לפרסום תוכן אמיתי —",
    demoNoticeLink: "צרו ופרסמו מממשק העבודה",
    searchPlaceholder: "חיפוש מאמרים, נושאים ומילות מפתח...",
    allCategories: "כל הקטגוריות",
    sortNewest: "החדשים ביותר",
    sortOldest: "הישנים ביותר",
    sortTitle: "לפי כותרת",
    searchButton: "חפש",
    filterAll: "הכל",
    trendingTopics: "נושאים בטרנד",
    noCategories: "אין קטגוריות עדיין.",
    categoriesLabel: "קטגוריות",
    previewLabel: "תצוגה לדוגמה",
    close: "סגור",
    previewFooter: "זהו מאמר לדוגמה. כדי לפרסם תוכן אמיתי בבלוג, צרו ופרסמו מאמרים מ",
    workspaceLink: "ממשק העבודה",
    minShort: "דק׳",
    faq: "שאלות נפוצות",
    emptyPage: "הדף פורסם, אך עדיין אין בו בלוקים להצגה.",
    contact: "יצירת קשר",
    learnMore: "מידע נוסף",
    sourceLink: "מקור",
    editModeLabel: "עריכת אדמין",
    editSelectArticle: "סמן כתבה לעריכה",
    editDeselectArticle: "בטל סימון כתבה",
    editClearSelection: "ביטול",
    openInStudio: "פתח בסטודיו",
    features: [
      { title: "מדריכים", description: "הוראות מעשיות ליישום SEO, שיווק ואוטומציה בתוך הארגון." },
      { title: "מחקר", description: "ניתוחים, טרנדים ותובנות מבוססות נתונים מהשטח." },
      { title: "כלי AI", description: "המלצות על כלי בינה מלאכותית לשיווק, תוכן ואוטומציה." },
      { title: "קהילה", description: "ידע מקצועי, שיתופי פעולה ותובנות ממומחי צמיחה." },
    ],
  },
  en: {
    metaTitle: "Mendeles Insights — Blog",
    metaDescription: "Insights, guides, and research for digital growth — the Mendeles Insights blog.",
    mastheadKicker: "Mendeles Insights",
    mastheadTitle: "Mendeles News",
    mastheadSubtitle: "Interesting news and articles from Israel and around the world",
    articles: "Articles",
    categories: "Categories",
    lastUpdate: "Last updated",
    allArticles: "All articles",
    inArchive: "in archive",
    noResults: "No articles match the current filters.",
    loadMore: "Load more articles",
    featured: "Featured",
    readArticle: "Read article",
    readMore: "Read more",
    readingMinutes: "min read",
    noDate: "No date",
    team: "Mendeles Team",
    search: "Search",
    newsletter: "Newsletter signup",
    navLabel: "Blog categories",
    siteNavLabel: "Main navigation",
    home: "Mendeles",
    blog: "Blog",
    tools: "Tools",
    breaking: "Breaking",
    sportsDesk: "Sports desk",
    sportsSubtitle: "Translated match reports and analysis from international football coverage",
    bookmarkAdd: "Bookmark",
    bookmarkRemove: "Remove bookmark",
    demoNotice: "Showing demo content — publish articles from the workspace to replace it.",
    demoNoticeTitle: "Demo blog preview",
    demoNoticeBody: "No published articles in production yet. Showing editorial demo posts. To publish real content —",
    demoNoticeLink: "create and publish from the workspace",
    searchPlaceholder: "Search articles, topics, and keywords...",
    allCategories: "All categories",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    sortTitle: "By title",
    searchButton: "Search",
    filterAll: "All",
    trendingTopics: "Trending topics",
    noCategories: "No categories yet.",
    categoriesLabel: "Categories",
    previewLabel: "Demo preview",
    close: "Close",
    previewFooter: "This is a demo article. To publish real blog content, create and publish from the",
    workspaceLink: "workspace",
    minShort: "min",
    faq: "FAQ",
    emptyPage: "This page is published but has no visible blocks yet.",
    contact: "Contact us",
    learnMore: "Learn more",
    sourceLink: "Source",
    editModeLabel: "Admin edit",
    editSelectArticle: "Select article for editing",
    editDeselectArticle: "Deselect article",
    editClearSelection: "Clear",
    openInStudio: "Open in studio",
    features: [
      { title: "Guides", description: "Practical playbooks for implementing SEO, marketing, and automation in your organization." },
      { title: "Research", description: "Analysis, trends, and data-driven insights from the field." },
      { title: "AI Tools", description: "Recommendations for AI tools across marketing, content, and automation." },
      { title: "Community", description: "Expert knowledge, collaboration, and insights from growth practitioners." },
    ],
  },
  ar: {
    metaTitle: "Mendeles Insights — المدونة",
    metaDescription: "رؤى وأدلة وأبحاث للنمو الرقمي — مدونة Mendeles Insights.",
    mastheadKicker: "Mendeles Insights",
    mastheadTitle: "أخبار Mendeles",
    mastheadSubtitle: "أخبار ومقالات شيّقة من البلاد والعالم",
    articles: "مقالات",
    categories: "فئات",
    lastUpdate: "آخر تحديث",
    allArticles: "كل المقالات",
    inArchive: "في الأرشيف",
    noResults: "لا توجد مقالات تطابق عوامل التصفية الحالية.",
    loadMore: "تحميل المزيد من المقالات",
    featured: "مميّز",
    readArticle: "اقرأ المقال",
    readMore: "اقرأ المزيد",
    readingMinutes: "دقائق قراءة",
    noDate: "بدون تاريخ",
    team: "فريق Mendeles",
    search: "بحث",
    newsletter: "الاشتراك في النشرة",
    navLabel: "فئات المدونة",
    siteNavLabel: "التنقل الرئيسي",
    home: "Mendeles",
    blog: "المدونة",
    tools: "أدوات",
    breaking: "عاجل",
    sportsDesk: "قسم الرياضة",
    sportsSubtitle: "تقارير وتحليلات مترجمة عن كرة القدم وعالم الرياضة",
    bookmarkAdd: "حفظ إشارة",
    bookmarkRemove: "إزالة الإشارة",
    demoNotice: "عرض محتوى تجريبي — انشر مقالات من مساحة العمل لاستبداله.",
    demoNoticeTitle: "معاينة مدونة تجريبية",
    demoNoticeBody: "لا توجد مقالات منشورة في الإنتاج بعد. تُعرض مقالات تحريرية للعرض. لنشر محتوى حقيقي —",
    demoNoticeLink: "أنشئ وانشر من مساحة العمل",
    searchPlaceholder: "ابحث في المقالات والمواضيع والكلمات المفتاحية...",
    allCategories: "كل الفئات",
    sortNewest: "الأحدث أولاً",
    sortOldest: "الأقدم أولاً",
    sortTitle: "حسب العنوان",
    searchButton: "بحث",
    filterAll: "الكل",
    trendingTopics: "مواضيع رائجة",
    noCategories: "لا توجد فئات بعد.",
    categoriesLabel: "فئات",
    previewLabel: "معاينة تجريبية",
    close: "إغلاق",
    previewFooter: "هذه مقالة تجريبية. لنشر محتوى حقيقي في المدونة، أنشئ وانشر من",
    workspaceLink: "مساحة العمل",
    minShort: "د",
    faq: "أسئلة شائعة",
    emptyPage: "الصفحة منشورة لكن لا توجد كتل للعرض بعد.",
    contact: "تواصل معنا",
    learnMore: "اعرف المزيد",
    sourceLink: "المصدر",
    editModeLabel: "تحرير المسؤول",
    editSelectArticle: "تحديد مقالة للتحرير",
    editDeselectArticle: "إلغاء تحديد المقالة",
    editClearSelection: "إلغاء",
    openInStudio: "فتح في الاستوديو",
    features: [
      { title: "أدلة", description: "خطط عملية لتطبيق SEO والتسويق والأتمتة داخل المؤسسة." },
      { title: "أبحاث", description: "تحليلات واتجاهات ورؤى مبنية على بيانات من الميدان." },
      { title: "أدوات AI", description: "توصيات لأدوات الذكاء الاصطناعي في التسويق والمحتوى والأتمتة." },
      { title: "مجتمع", description: "معرفة خبراء وتعاون ورؤى من ممارسي النمو." },
    ],
  },
} as const;

export function editorialCopy(locale: string): (typeof COPY)[keyof typeof COPY] {
  if (locale === "en") return COPY.en;
  if (locale === "ar") return COPY.ar;
  return COPY.he;
}

export function dateLocale(locale: string): string {
  if (locale === "en") return "en-US";
  if (locale === "ar") return "ar";
  return "he-IL";
}

export function sortLocale(locale: string): string {
  if (locale === "en") return "en";
  if (locale === "ar") return "ar";
  return "he";
}
