export type EditorialLocale = "he" | "en";

const COPY = {
  he: {
    metaTitle: "Mendeles Insights — בלוג",
    metaDescription: "תובנות, מדריכים ומחקר לצמיחה דיגיטלית — בלוג Mendeles Insights.",
    mastheadKicker: "Mendeles Insights",
    mastheadTitle: "חדר חדשות דיגיטלי",
    mastheadSubtitle:
      "מדריכים, מחקרים ותובנות על SEO, שיווק, AI ואוטומציה — עיצוב עיתונאי לצוותי צמיחה.",
    articles: "מאמרים",
    categories: "קטגוריות",
    lastUpdate: "עדכון אחרון",
    allArticles: "כל המאמרים",
    inArchive: "במאגר",
    noResults: "לא נמצאו מאמרים עבור הסינון הנוכחי.",
    loadMore: "טען עוד מאמרים",
    featured: "מומלץ",
    readArticle: "קרא את המאמר",
    readMore: "קרא עוד",
    readingMinutes: "דקות קריאה",
    noDate: "ללא תאריך",
    team: "צוות Mendeles",
    search: "חיפוש",
    newsletter: "הרשמה לניוזלטר",
    navLabel: "קטגוריות בלוג",
    breaking: "מבזק",
    sportsDesk: "מדור ספורט",
    sportsSubtitle: "כתבות מתורגמות וניתוחים על כדורגל ועולם הספורט",
    bookmarkAdd: "שמור סימניה",
    bookmarkRemove: "הסר סימניה",
    demoNotice: "מציגים תוכן הדגמה — פרסמו מאמרים מה-workspace כדי להחליף.",
    demoNoticeTitle: "תצוגת בלוג לדוגמה",
    demoNoticeBody: "אין עדיין מאמרים מפורסמים בפרודקשן. מוצגים מאמרי עריכה לדוגמה. לפרסום תוכן אמיתי —",
    demoNoticeLink: "צרו ופרסמו מממשק העבודה",
    searchPlaceholder: "חיפוש מאמרים, נושאים ומילות מפתח...",
    allCategories: "כל הקטגוריות",
    sortNewest: "החדשים ביותר",
    sortOldest: "הישנים ביותר",
    sortTitle: "לפי כותרת",
    searchButton: "חפש",
    filterAll: "הכל",
    trendingTopics: "נושאים בטרנד",
    noCategories: "אין קטגוריות עדיין.",
    categoriesLabel: "קטגוריות",
    previewLabel: "תצוגה לדוגמה",
    close: "סגור",
    previewFooter: "זהו מאמר לדוגמה. כדי לפרסם תוכן אמיתי בבלוג, צרו ופרסמו מאמרים מ",
    workspaceLink: "ממשק העבודה",
    minShort: "דק׳",
    faq: "שאלות נפוצות",
    emptyPage: "הדף פורסם, אך עדיין אין בו בלוקים להצגה.",
    contact: "יצירת קשר",
    sourceLink: "מקור",
    features: [
      { title: "מדריכים", description: "הוראות מעשיות ליישום SEO, שיווק ואוטומציה בתוך הארגון." },
      { title: "מחקר", description: "ניתוחים, טרנדים ותובנות מבוססות נתונים מהשטח." },
      { title: "כלי AI", description: "המלצות על כלי בינה מלאכותית לשיווק, תוכן ואוטומציה." },
      { title: "קהילה", description: "ידע מקצועי, שיתופי פעולה ותובנות ממומחי צמיחה." },
    ],
  },
  en: {
    metaTitle: "Mendeles Insights — Blog",
    metaDescription: "Insights, guides, and research for digital growth — the Mendeles Insights blog.",
    mastheadKicker: "Mendeles Insights",
    mastheadTitle: "Digital Newsroom",
    mastheadSubtitle:
      "Guides, research, and insights on SEO, marketing, AI, and automation — editorial-grade growth coverage.",
    articles: "Articles",
    categories: "Categories",
    lastUpdate: "Last updated",
    allArticles: "All articles",
    inArchive: "in archive",
    noResults: "No articles match the current filters.",
    loadMore: "Load more articles",
    featured: "Featured",
    readArticle: "Read article",
    readMore: "Read more",
    readingMinutes: "min read",
    noDate: "No date",
    team: "Mendeles Team",
    search: "Search",
    newsletter: "Newsletter signup",
    navLabel: "Blog categories",
    breaking: "Breaking",
    sportsDesk: "Sports desk",
    sportsSubtitle: "Translated match reports and analysis from international football coverage",
    bookmarkAdd: "Bookmark",
    bookmarkRemove: "Remove bookmark",
    demoNotice: "Showing demo content — publish articles from the workspace to replace it.",
    demoNoticeTitle: "Demo blog preview",
    demoNoticeBody: "No published articles in production yet. Showing editorial demo posts. To publish real content —",
    demoNoticeLink: "create and publish from the workspace",
    searchPlaceholder: "Search articles, topics, and keywords...",
    allCategories: "All categories",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    sortTitle: "By title",
    searchButton: "Search",
    filterAll: "All",
    trendingTopics: "Trending topics",
    noCategories: "No categories yet.",
    categoriesLabel: "Categories",
    previewLabel: "Demo preview",
    close: "Close",
    previewFooter: "This is a demo article. To publish real blog content, create and publish from the",
    workspaceLink: "workspace",
    minShort: "min",
    faq: "FAQ",
    emptyPage: "This page is published but has no visible blocks yet.",
    contact: "Contact us",
    sourceLink: "Source",
    features: [
      { title: "Guides", description: "Practical playbooks for implementing SEO, marketing, and automation in your organization." },
      { title: "Research", description: "Analysis, trends, and data-driven insights from the field." },
      { title: "AI Tools", description: "Recommendations for AI tools across marketing, content, and automation." },
      { title: "Community", description: "Expert knowledge, collaboration, and insights from growth practitioners." },
    ],
  },
} as const;

export function editorialCopy(locale: string): (typeof COPY)[keyof typeof COPY] {
  return locale === "en" ? COPY.en : COPY.he;
}

export function dateLocale(locale: string): string {
  return locale === "en" ? "en-US" : "he-IL";
}

export function sortLocale(locale: string): string {
  return locale === "en" ? "en" : "he";
}
