# Generated by Django 5.1.15 on 2026-07-13 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenant_credits_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('goal', models.TextField(blank=True, default='')),
                ('campaign_type', models.CharField(choices=[('traffic', 'Traffic'), ('tool_launch', 'Tool Launch'), ('viral', 'Viral'), ('tutorial', 'Tutorial'), ('product', 'Product'), ('announcement', 'Announcement'), ('news', 'News')], default='traffic', max_length=40)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('funny', 'Funny'), ('emotional', 'Emotional'), ('curious', 'Curious'), ('shocking', 'Shocking')], default='professional', max_length=40)),
                ('target_audience', models.CharField(blank=True, default='', max_length=500)),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('captions_json', models.JSONField(blank=True, default=dict)),
                ('hashtags_json', models.JSONField(blank=True, default=dict)),
                ('cta', models.CharField(blank=True, default='', max_length=500)),
                ('main_idea', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('media_prompt', models.TextField(blank=True, default='')),
                ('video_prompt', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='draft', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, default='Asia/Jerusalem', max_length=64)),
                ('buffer_update_ids', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('publish_log', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_campaigns', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'social_campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='social_camp_tenant__fa37ec_idx')],
            },
        ),
    ]
