# Generated by Django 5.1.15 on 2026-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcampaign',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
