/**
 * Per-table pixel coordinates for public/images/pais-lotto-form.png (244×670).
 * Generated by scanning each oval per table band (layouts differ between tables).
 */
import cellData from "./pais-form-cells.json";

export const PAIS_FORM_IMAGE = "/images/pais-lotto-form.png";
export const PAIS_FORM_WIDTH = cellData.w;
export const PAIS_FORM_HEIGHT = cellData.h;

/** Official PAIS form rows — 7 + 10 + 10 + 10 cells. */
export const PAIS_ROWS: readonly (readonly number[])[] = [
  [1, 2, 3, 4, 5, 6, 7],
  [8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
  [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
  [28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
] as const;

export const PAIS_STRONG = [1, 2, 3, 4, 5, 6, 7] as const;

type CellPair = [number, number];
type CellRow = Record<string, CellPair>;

const MAIN_CELLS = cellData.main as unknown as CellRow[];
const STRONG_CELLS = cellData.strong as unknown as CellRow[];

export interface MarkPoint {
  x: number;
  y: number;
}

/** Horizontal bar sized to fit inside red ovals (~14×14 px cells). */
export const MARK_WIDTH = 13;
export const MARK_HEIGHT = 2.5;

function tableIndex(setIndex: number): number | null {
  if (setIndex < 1 || setIndex > MAIN_CELLS.length) return null;
  return setIndex - 1;
}

export function markForMainNumber(setIndex: number, num: number): MarkPoint | null {
  const ti = tableIndex(setIndex);
  if (ti === null) return null;
  const pt = MAIN_CELLS[ti][String(num)];
  if (!pt) return null;
  return { x: pt[0], y: pt[1] };
}

export function markForStrongNumber(setIndex: number, strong: number): MarkPoint | null {
  const ti = tableIndex(setIndex);
  if (ti === null || strong < 1 || strong > 7) return null;
  const pt = STRONG_CELLS[ti][String(strong)];
  if (!pt) return null;
  return { x: pt[0], y: pt[1] };
}

export function marksForTable(
  setIndex: number,
  numbers: number[],
  strong: number,
): MarkPoint[] {
  const pts: MarkPoint[] = [];
  for (const n of numbers) {
    const p = markForMainNumber(setIndex, n);
    if (p) pts.push(p);
  }
  const sp = markForStrongNumber(setIndex, strong);
  if (sp) pts.push(sp);
  return pts;
}
