# Generated by Django 5.1.15 on 2026-06-28 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('suspended', 'מושהה'), ('trial', 'ניסיון')], default='active', max_length=20)),
                ('settings_json', models.JSONField(blank=True, db_column='settings', default=dict)),
            ],
            options={
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['status'], name='tenants_status_80d9b6_idx')],
            },
        ),
    ]
